name: tugas_besar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: 0.13.5
  introduction_screen: 3.0.2
  google_fonts: ^3.0.1
  lottie: 2.0.0
  convex_bottom_bar: 3.1.0+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

